#!/bin/sh
echo "Enter username:"
read UN
if grep -q $UN /etc/passwd; then
	if pgrep -u $UN; then
		while ($(sudo kill $(pgrep -u $UN)))
		do echo "Process killed"
		done
		sudo userdel $UN
		echo "$UN deleted"
	else
		echo "User is not active"
	fi
else
	echo "User does not exist"
fi
